package com.yh.jiran.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yh.jiran.module.home.model.entity.HomeStar;
import com.yh.jiran.module.home.model.entity.SearchHistory;
import com.yh.jiran.module.login.model.entity.User;
import com.yh.jiran.module.test.model.entity.TestUser;

import com.yh.jiran.greendao.HomeStarDao;
import com.yh.jiran.greendao.SearchHistoryDao;
import com.yh.jiran.greendao.UserDao;
import com.yh.jiran.greendao.TestUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeStarDaoConfig;
    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig testUserDaoConfig;

    private final HomeStarDao homeStarDao;
    private final SearchHistoryDao searchHistoryDao;
    private final UserDao userDao;
    private final TestUserDao testUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeStarDaoConfig = daoConfigMap.get(HomeStarDao.class).clone();
        homeStarDaoConfig.initIdentityScope(type);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        testUserDaoConfig = daoConfigMap.get(TestUserDao.class).clone();
        testUserDaoConfig.initIdentityScope(type);

        homeStarDao = new HomeStarDao(homeStarDaoConfig, this);
        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        testUserDao = new TestUserDao(testUserDaoConfig, this);

        registerDao(HomeStar.class, homeStarDao);
        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(User.class, userDao);
        registerDao(TestUser.class, testUserDao);
    }
    
    public void clear() {
        homeStarDaoConfig.clearIdentityScope();
        searchHistoryDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        testUserDaoConfig.clearIdentityScope();
    }

    public HomeStarDao getHomeStarDao() {
        return homeStarDao;
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public TestUserDao getTestUserDao() {
        return testUserDao;
    }

}
