package com.yh.jiran.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yh.jiran.module.test.model.entity.TestUser;

import com.yh.jiran.greendao.TestUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testUserDaoConfig;

    private final TestUserDao testUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testUserDaoConfig = daoConfigMap.get(TestUserDao.class).clone();
        testUserDaoConfig.initIdentityScope(type);

        testUserDao = new TestUserDao(testUserDaoConfig, this);

        registerDao(TestUser.class, testUserDao);
    }
    
    public void clear() {
        testUserDaoConfig.clearIdentityScope();
    }

    public TestUserDao getTestUserDao() {
        return testUserDao;
    }

}
